## グルーピング

In [3]:
import pandas as pd

path = "/content/drive/Othercomputers/DATACANVAS/github/learning_v2/samurai/openpyxl_cource/"

# Excelファイルを読み込む
df = pd.read_excel(path + '/' + 'Chapter11_1.xlsx', sheet_name='Sheet1')

# 年代別に「得点」列の平均値を計算する
result = df.groupby('年代')['得点'].max()

print(result)

年代
20    60
30    90
Name: 得点, dtype: int64

## 条件に応じたデータ抽出

In [ ]:
import pandas as pd


path = "/content/drive/Othercomputers/DATACANVAS/github/learning_v2/samurai/openpyxl_cource/"
# Excelファイルを読み込む
df = pd.read_excel(path + '/' + 'Chapter11_2.xlsx', sheet_name='Sheet1')
display(df)
print("------------------------------")

df = df[df['年代'] >= 40]
display(df)

   名前  年代  得点
0  一郎  30  40
1  二郎  40  50
2  三郎  50  60

------------------------------

   名前  年代  得点
1  二郎  40  50
2  三郎  50  60

## パターンマッチング

In [ ]:
# ^[0-9]{3}-[0-9]{4}-[0-9]{4}$
# 説明: 0-9の数値で始まり、3つ続く。
# その後、- を入れ、0-9のどれかが4つ続く。
# その後、- を入れ、最後に0-9のどれかが4つ続く。

import pandas as pd
path = "/content/drive/Othercomputers/DATACANVAS/github/learning_v2/samurai/openpyxl_cource/"

# Excelファイルの読み込み
df = pd.read_excel(path + "/" + 'Chapter11_3.xlsx', sheet_name='Sheet1')

# 変数patternに電話番号の正規表現を格納、文字列のため'を使用
# 070-1234-5678: 検索してほしい
# 070-123-124: マッチしてほしくない
# 070_1234_5678: マッチしてほしくない
pattern = r'^[0-9]{3}-[0-9]{4}-[0-9]{4}$'

# 電話番号列につきstr.contains()でpatternに一致する行のみdf_filteredに格納
df_filtered = df[df['電話番号'].str.contains(pattern, na=False)]

print(df_filtered)

            電話番号
1  012-3456-7890

## 結合

In [4]:
import pandas as pd


# 処理対象のファイル名のリストを格納
file_list = ['Chapter11_4.xlsx', 'Chapter11_5.xlsx']

# 結合後のデータを格納するための空のデータフレームを作成
df = pd.DataFrame()

# ファイルを一つずつ処理する
path = "/content/drive/Othercomputers/DATACANVAS/github/learning_v2/samurai/openpyxl_cource/"
for file_name in file_list:
    # Excelファイルを読み込む
    temp_df = pd.read_excel(path + "/" + file_name)

    # データフレームの列名を指定
    temp_df.columns = ['名前', '年代', '得点']

    # concat()でデータフレームを連結
    df = pd.concat([df, temp_df], ignore_index=True)

print(df)

   名前  年代  得点
0  一郎  20  40
1  二郎  20  50
2  三郎  20  60
3  四郎  30  70
4  五郎  30  80
5  六郎  30  90

In [8]:
import pandas as pd


# 処理対象のファイル名のリストを格納
file_list = ['Chapter11_4.xlsx', 'Chapter11_5.xlsx']

# 結合後のデータを格納するための空のデータフレームを作成
df = pd.DataFrame()

# ファイルを一つずつ処理する
path = "/content/drive/Othercomputers/DATACANVAS/github/learning_v2/samurai/openpyxl_cource/"

df_11_4 = pd.read_excel(path + "/" + 'Chapter11_4.xlsx')
df_11_5 = pd.read_excel(path + "/" + 'Chapter11_5.xlsx')
df = pd.concat([df_11_4, df_11_5], ignore_index=True, axis=0)

print(df)

   名前  年代  得点
0  一郎  20  40
1  二郎  20  50
2  三郎  20  60
3  四郎  30  70
4  五郎  30  80
5  六郎  30  90