In [9]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## ワーク1

In [10]:
import pandas as pd

In [11]:
path = "/content/drive/Othercomputers/DATACANVAS/github/learning_v2/samurai/openpyxl_cource/"

In [12]:
# 【ワーク①】売上管理の集計結果を「売上管理」シートに書き出す

# データフレームを作成する
df = pd.DataFrame(data={
    '商品名': ['人気商品A', '商品B', '人気商品C', '人気商品A', '商品B', '商品D'],
    '売上金額': [1000, 2000, 3000, 4000, 5000, 6000],
    '売上コスト': [800, 1500, 2400, 800, 1500, 2200]
})
display(df.head())

     商品名  売上金額  売上コスト
0  人気商品A  1000    800
1    商品B  2000   1500
2  人気商品C  3000   2400
3  人気商品A  4000    800
4    商品B  5000   1500

In [13]:
# 商品ごとに売上金額と売上コストを合計
grouped = df.groupby('商品名').agg({'売上金額': 'sum', '売上コスト': 'sum'})

# 利益率を求める
grouped['利益率'] = ((grouped['売上金額'] - grouped['売上コスト']) / grouped['売上金額']) * 100

display(grouped.head())

       売上金額  売上コスト        利益率
商品名
人気商品A  5000   1600  68.000000
人気商品C  3000   2400  20.000000
商品B    7000   3000  57.142857
商品D    6000   2200  63.333333

In [14]:
# Excelファイルを作成する
writer = pd.ExcelWriter('売上管理表.xlsx')

# DataFrameオブジェクトをExcelファイルに書き込む
grouped.to_excel(writer, sheet_name='売上管理', index=True)

## ワーク2

In [15]:
# 【ワーク②】人気商品の抽出結果を「人気商品」シートに書き出す

# データフレームから「人気」とついている商品を抽出
popular_items = df[df['商品名'].str.contains('人気')]

# Excelファイルに抽出結果を追加
popular_items.to_excel(writer, sheet_name='人気商品', index=False)

# Excelファイルを閉じる
writer.close()

## ワーク3

In [16]:
import openpyxl

# Excelファイルの読み込み
book = openpyxl.load_workbook('売上管理表.xlsx')

# ワークシートの選択
sheet = book.active

# データの読み込み
data2 = sheet.values

# ヘッダーの読み込み
cols = next(data2)

# データフレームの作成
df = pd.DataFrame(data2, columns=cols)

display(df)

     商品名  売上金額  売上コスト        利益率
0  人気商品A  5000   1600  68.000000
1  人気商品C  3000   2400  20.000000
2    商品B  7000   3000  57.142857
3    商品D  6000   2200  63.333333